In [ ]:
#######################################################
#######################################################
############    COPYRIGHT - DATA SOCIETY   ############
#######################################################
#######################################################

## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 1 ##

## NOTE: To run individual pieces of code, select the line of code and
##       press ctrl + enter for PCs or command + enter for Macs




In [2]:
#=================================================-
#### Slide 7: Creating arrays  ####

# Import numpy as 'np' sets 'np' as the shortcut/alias.
import numpy as np

# Create an array from a list. 
arr = np.array([17, -10, 16.8, 11])
print(arr)

# Check the type of the object.
print(type(arr))




[ 17.  -10.   16.8  11. ]
<class 'numpy.ndarray'>


In [ ]:
#=================================================-
#### Slide 8: Data type in arrays  ####

# Check the data type stored in the array.
print(arr.dtype)




In [ ]:
#=================================================-
#### Slide 9: Using ndarray  ####

x = np.array([3, 19, 7, 11])
print(x)




In [ ]:
print(x.shape)

In [ ]:
print(x.size)

In [ ]:
print(x.ndim)

In [ ]:
print(x.dtype)

In [ ]:
print(x[0])

In [ ]:
#=================================================-
#### Slide 11: Building an array with linspace  ####

y = np.linspace(-2, -1, 25)
print(y)




In [ ]:
result = np.linspace(1, 5, 10)
print(result)

In [ ]:
print(result.shape)

In [ ]:
#=================================================-
#### Slide 12: Alternative ways of accessing functions  ####

from numpy import array, linspace
x = array([0.01, 0.45, -0.3])
y = linspace(0, 1, 50)




In [ ]:
print(y)

In [ ]:
result = np.logspace(1, 2, 5)
print(result)

In [ ]:
#=================================================-
#### Slide 16: Arrays vs. lists  ####

mixed_array = np.array([1, 2, "apple", "XYZ", 5.5])
print(mixed_array)
print(type(mixed_array))
print(mixed_array.dtype)




In [ ]:
#=================================================-
#### Slide 17: Arrays vs lists (cont'd)  ####

print(mixed_array.dtype)
mixed_array = np.array([3, 12, 5.56])
print(mixed_array)
print(mixed_array.dtype)




In [ ]:
#=================================================-
#### Slide 19: Arrays from sequences (cont'd)  ####

rng = np.arange(0, 51)
print(rng)




In [3]:
#=================================================-
#### Slide 20: Arrays from sequences - using a step size  ####

evens = np.arange(0, 23, 2)
print(evens)

quarters = np.arange(0, 1, .25)  #<- contains 0 to 0.75
print(quarters)


#######################################################
####  CONGRATULATIONS ON COMPLETING THIS MODULE!   ####
#######################################################


[ 0  2  4  6  8 10 12 14 16 18 20 22]
[0.   0.25 0.5  0.75]


In [ ]:
#######################################################
#######################################################
############    COPYRIGHT - DATA SOCIETY   ############
#######################################################
#######################################################

## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 2 ##

## NOTE: To run individual pieces of code, select the line of code and
##       press ctrl + enter for PCs or command + enter for Macs




In [9]:
#=================================================-
#### Slide 2: Helper functions: min and max  ####

import numpy as np

# Generate 5 numbers between 15 and 19.
x = np.linspace(15, 19, 5)
print(x)
# Find the min of x.
y=np.amin(x)
print(y)
# Find the max of x.
z= np.amax(x)
print(z)



[15. 16. 17. 18. 19.]
15.0
19.0


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Użycie funkcji numpy.amax
max_val = np.amax(arr)
print(max_val)

6


In [10]:
#=================================================-
#### Slide 3: Helper functions: argmin and argmax  ####

# Obtain index of max value
a= np.argmax(x)
print(a)
# Obtain index of min value
b= np.argmin(x)
print(b)



4
0


In [7]:
#=================================================-
#### Slide 4: Helper functions: sum  ####

# Find the max of x.
c = np.sum(x)
print(c)



85.0


In [9]:
#=================================================-
#### Slide 5: Helper functions: mean and median  ####

# Find the mean of x.
d = np.mean(x)
print(d)
# Find the median of x.
e= np.median(x)
print(e)



17.0
17.0


In [10]:
#=================================================-
#### Slide 6: Helper functions: digitize  ####

# Filter array using digitize
bins = np.array([15, 17])
f= np.digitize(x,bins)
print(f)




[1 1 2 2 2]


In [11]:
x = np.array([0.5, 1.5, 2.5, 5.5, 15.5])

# Granice przedziałów
bins = np.array([0, 2, 4, 10])

# Przypisanie indeksów przedziałów
result = np.digitize(x, bins)

print(result)

[1 1 2 3 4]


In [12]:
#=================================================-
#### Slide 7: Helper functions: expand and squeeze  ####

# Expand dimensions of the array horizontally
g= np.expand_dims(x,axis=0)
print(g)
# Expand dimensions of the array vertically
h= np.expand_dims(x,axis=1)
print(h)




[[ 0.5  1.5  2.5  5.5 15.5]]
[[ 0.5]
 [ 1.5]
 [ 2.5]
 [ 5.5]
 [15.5]]


In [3]:
#=================================================-
#### Slide 8: Helper functions: expand and squeeze (cont'd)  ####

# Define an array in the format of lists
y = np.array([[10],[25],[28],[30]])
# Reduce dimensions of the array
np.squeeze(y)




array([10, 25, 28, 30])

In [4]:
#=================================================-
#### Slide 9: Convert an array to a list  ####

evens = np.arange(0, 23, 2)
print(list(evens))




[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]


In [5]:
#=================================================-
#### Slide 10: Operations on arrays  ####

# Save two arrays as variables.
a = np.array([1,1,1,1])
b = np.array([2,2,2,2])

# Addition of arrays.
print(a + b)

# Subtraction of arrays.
print(a - b)
# Multiplication of arrays.
print(a * b)
# Division of arrays.
print(a / b)




[3 3 3 3]
[-1 -1 -1 -1]
[2 2 2 2]
[0.5 0.5 0.5 0.5]


In [ ]:
#=================================================-
#### Slide 12: Set operations  ####

# Retrieving common elements present in the arrays.
np.intersect1d(a, b, return_indices=True)

# Retrieving elements present in both the arrays.
np.union1d(a, b)
# Retrives the elements that are present only in the first array.
np.setdiff1d(a, b)




In [ ]:
#=================================================-
#### Slide 13: Stacking arrays  ####

# Stacking arrays horizontally.
np.hstack((a,b))

# Stacking arrays vertically.
np.vstack((a,b))




In [ ]:
#=================================================-
#### Slide 15: Mathematical functions on arrays  ####

print(np.abs(-3))
print(np.abs([-2, -7, 1]))
nums = np.arange(20, 30, .5)
print(len(nums))




In [ ]:
#=================================================-
#### Slide 16: User-defined functions on arrays  ####

# Define a function to multiply every element in array with 3 and add 1
def some_calculation(arr):
    return 3*arr+1
    
print(some_calculation(nums))


#######################################################
####  CONGRATULATIONS ON COMPLETING THIS MODULE!   ####
#######################################################


In [ ]:
#######################################################
#######################################################
############    COPYRIGHT - DATA SOCIETY   ############
#######################################################
#######################################################

## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 3 ##

## NOTE: To run individual pieces of code, select the line of code and
##       press ctrl + enter for PCs or command + enter for Macs




In [2]:
#=================================================-
#### Slide 2: Recap: arrays  ####

# Import numpy as 'np' sets 'np' as the shortcut/alias.
import numpy as np




In [ ]:
#=================================================-
#### Slide 3: Accessing array values  ####

nums = np.arange(20, 30, .5)

print(nums[1])  #<- get the second element

print(nums[0:3]) #<- get the first three elements




In [ ]:
#=================================================-
#### Slide 4: Logical filtering  ####

print(nums)

large_nums = nums[nums > 26]
print(large_nums)




In [1]:
#=================================================-
#### Slide 5: Logical filtering (cont'd)  ####

print(nums)

large_nums = nums[nums > 26]
print(large_nums)




NameError: name 'nums' is not defined

In [ ]:
#=================================================-
#### Slide 6: Two-dimensional arrays  ####

mat = np.array([
        [8, 2, 6, 8],
        [4, 5, 7, 2],
        [3, 9, 7, 1]
       ])
print(mat)




In [ ]:
#=================================================-
#### Slide 8: Two-dimensional arrays - shape (cont'd)  ####

print(mat.shape) #<- 3 rows and 4 columns -- returned as a tuple
nrows, ncols = mat.shape
print(nrows)




In [ ]:
#=================================================-
#### Slide 9: Two-dimensional arrays - extracting elements  ####

print(mat[1, 3]) #<- 2nd row 4th column - remember that indexing starts at 0!




In [ ]:
#=================================================-
#### Slide 10: Two-dimensional arrays - rows  ####

print(mat[0, :]) #<- first row
print(mat[0, 0:2]) #<- first row and just first 2 columns




In [ ]:
#=================================================-
#### Slide 11: Two-dimensional arrays - columns  ####

print(mat[:, 2]) #<- 3rd column
print(mat[1:3, 2]) #<- 3rd column but skipping over the first row
print(mat[1:3, 2:3]) #<- same as previous, but maintains the vertical structure of the column




In [ ]:
#=================================================-
#### Slide 13: Reshaping arrays  ####

arr = np.arange(1,13)
print(arr)
print(arr.reshape(3, 4))




In [ ]:
#=================================================-
#### Slide 15: Reshaping arrays (cont'd)  ####

print(arr.reshape(2,      #<- specify number of rows=2
                  2))     #<- number of columns=2 throws error




In [ ]:
#=================================================-
#### Slide 17: Exercise   ####




#######################################################
####  CONGRATULATIONS ON COMPLETING THIS MODULE!   ####
#######################################################
