## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 3 EXERCISE  ##
#### Please refer to module 1 of DataWranglingInPython - DataWranglingWithNumpy for Tasks 1-6 
#### Task 1
##### Create an array of 25 numbers between 1 and 100 (including 100) and save to `arr1` variable.
##### Print the type and data type of `arr1`.
#### Result:


In [3]:
import numpy as np
arr = np.linspace(1, 100, 25)
print(arr)

[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]


#### Task 2
##### Create an array of 20 numbers from 50 to 70 (excluding 70).
##### Use the `arange` function and assign the output to `arr2` variable.
#### Result:


In [5]:
arr2 = np.arange(50,70)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


#### Please refer to module 2 of DataWranglingInPython - DataWranglingWithNumpy for Tasks 3-6 
#### Task 3
##### Create an array of 10 numbers between 0 and 20 (including 20) and assign to `arr3` variable.
##### Use `linspace` function.
##### Find the max, min, their indices, sum and mean of the array.
#### Result:


In [6]:
import numpy as np
arr3 = np.linspace(0,20,10)
print(arr3)
a_max = np.max(arr3)
print(a_max)
a= np.argmax(arr3)
print(a)
a_min = np.min(arr3)
print(a_min)
b= np.argmin(arr3)
print(b)
a_sum = np.sum(arr3)
print(a_sum)
a_mean = np.mean(arr3)
print(a_mean)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
20.0
9
0.0
0
100.0
10.0


#### Task 4
##### Create two arrays of size 4 with the numbers 4, 5, 6, 4 in `array1` and 7, 2, 12, 16 in `array2`.
##### Find the `sum`,  `product`, `difference`, and `quotient` of `array1` and `array2`. Save the results as `array_sum`, `product`, `difference`, and `quotient` variables, respectively.
##### Perform the set operations `union` and `intersect` on the arrays.
##### Stack the arrays vertically and horizontally.
##### Print the results.
#### Result:


In [9]:
a = np.array([4,5,6,4])
b = np.array([7,2,12,16])
s= a+b
print(s)
p = a*b
print(p)
d = a-b
print(d)
q = a/b
print(q)

u = np.union1d(a,b)
print(u)
i = np.intersect1d(a,b)
print(i)
print(np.hstack((a,b)))

# Stacking arrays vertically.
print(np.vstack((a,b)))


[11  7 18 20]
[28 10 72 64]
[ -3   3  -6 -12]
[0.57142857 2.5        0.5        0.25      ]
[ 2  4  5  6  7 12 16]
[]
[ 4  5  6  4  7  2 12 16]
[[ 4  5  6  4]
 [ 7  2 12 16]]


#### Task 5
##### Compute the absolute value of each entry in the following array: `[5, -8, -66, 4]`.
##### Assign the operation to `abs_values` variable. Print the result.
##### Print the length of the `abs_values` array.
##### Print the 3rd element of `abs_values`.
#### Result:


In [11]:
abs_values = np.abs(np.array([5,-8,-66,4]))
print(abs_values)
print(len(abs_values))
print(abs_values[2])


[ 5  8 66  4]
4
66


#### Task 6
##### Print all numbers greater than 25 in `abs_values` array.
#### Result:


In [12]:
print(abs_values[abs_values>25])

[66]


#### Please refer to module 3 of DataWranglingInPython - DataWranglingWithNumpy for Tasks 7-8
#### Task 7
##### Create the following matrix with 3 rows and assign to variable `mat1`:
- [4, 5, 6]
- [8, 3, 2]
- [6, 7, 3]
##### Find the shape of the matrix.
#### Result:


In [3]:
import numpy as np
mat1 = np.array([[4,5,6],[8,3,2],[6,7,3]])
print(mat1.shape)

(3, 3)


#### Task 8
##### Find the value in the 2nd row and 3rd column of `mat1`.
##### Print the 2nd and 3rd rows.
##### Print the 1st column and rows up to the 2nd row.
##### Print all columns starting with column 2.
#### Result:


In [12]:
print(mat1[1,2])
print(mat1[1:,])
print(mat1[0:2,0])
print(mat1[:,1:])

2
[[8 3 2]
 [6 7 3]]
[4 8]
[[5 6]
 [3 2]
 [7 3]]


#### Bonus Task 1
##### Filter and print the elements greater than 5 in `mat1`.
##### Use a Boolean mask to filter all elements <= 5 and set them to 0.
##### Print the resulting matrix.
#### Result:


In [14]:
print(mat1[mat1>5])
mat1[mat1<=5] = 0
print(mat1)

[6 8 6 7]
[[0 0 6]
 [8 0 0]
 [6 7 0]]


#### Bonus Task 2
##### Use the `linspace` function to create a NumPy array of 16 numbers between 10 and 25 (inclusive) called `arr4`.
##### Reshape the array to a matrix of shape (4,4) and print it.
##### Reshape the array to a matrix with 8 rows and let Python infer the number of columns.
#### Result:


In [17]:
arr4 = np.linspace(10,25,16)
print(arr4)
print(arr4.reshape(4,4))



# arr4 = np.linspace(10,25,16).reshape(4,4)
# print(arr4)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]
[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]
 [22. 23. 24. 25.]]
